import { defineConfig } from 'tsup';

export default defineConfig({
		entry: ['src/**/*.ts'],
		format: ['esm'],
		splitting: true,
		minify: true,
		dts: true,
		clean: true,
		platform: 'node',
		tsconfig: './tsconfig.json',
		target: 'es2022',
		shims: true,
		bundle: true,
		treeshake: true,
		outDir: 'dist',
		external: [
			'vite',
			'util',
			'url',
			'events',
			'path',
			'fs',
			'assert',
			'stream',
			'constants',
			'readline',
			'module',
			'os',
		],
		onSuccess: 'chmod +x ./dist/index.js',
	});
